name: Godot Android Export

on:
  push:
    branches: [ "main" ]

jobs:
  export-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Export Android APK
        uses: primaryfeuer/godot-export@v4
        with:
          godot_version: "4.2.2"
          project_directory: "./first-person-shooting"
          export_type: "release"
          export_preset: "Android"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-game-android-apk
          path: first-person-shooting/build/
